version: '3.3'

services:
  gw-postgres: 
    container_name: gw-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gw-db
      POSTGRES_USER: gw-dev
      POSTGRES_PASSWORD: NARCIO
    volumes:
      - postgres:/data/postgres
    networks: 
      - base
 
      
  gw-api: 
    container_name: gw-api
    image: node:latest
    command: yarn start:dev
    depends_on:
      - gw-postgres
    working_dir: /app
    environment: 
      POSTGRES_HOST: gw-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: gw-dev
      POSTGRES_PASSWORD: NARCIO
      POSTGRES_DB: gw-db
    networks:
      - base
    ports: 
      - 3000:3000
    volumes: 
      - ./gw-api/:/app
    
networks: 
  base:
volumes:
  postgres: